# data.py – all static lookup tables for Smart Crop Advisor v3

CROP_EMOJI = {
    "Rice":"🍚","Maize":"🌽","Chickpea":"🫘","Kidney Beans":"🫘",
    "Pigeon Peas":"🫘","Moth Beans":"🫘","Mung Bean":"🫘","Black Gram":"🫘",
    "Lentil":"🫘","Pomegranate":"🍎","Banana":"🍌","Mango":"🥭",
    "Grapes":"🍇","Watermelon":"🍉","Muskmelon":"🍈","Apple":"🍎",
    "Orange":"🍊","Papaya":"🍈","Coconut":"🥥","Cotton":"🌿",
    "Jute":"🌿","Coffee":"☕",
}

CROP_INFO = {
    "Rice":         {"tip":"Requires flooded fields & high humidity.",
                     "season":"Kharif","water_mm":1200,"duration":"90–150 days",
                     "profit":"Medium","market_price":22,"category":"Cereal",
                     "soil_types":["Clay","Loamy Clay"],"min_om":1.5,
                     "pest_risk":"High","diseases":["Blast","Brown planthopper","Sheath blight"]},
    "Maize":        {"tip":"Needs well-drained soil. Sensitive to waterlogging.",
                     "season":"Kharif / Rabi","water_mm":600,"duration":"80–110 days",
                     "profit":"Medium","market_price":18,"category":"Cereal",
                     "soil_types":["Loamy","Sandy Loam"],"min_om":1.2,
                     "pest_risk":"Medium","diseases":["Fall Armyworm","Northern Leaf Blight","Smut"]},
    "Chickpea":     {"tip":"Drought-tolerant. Grows well in cool, dry conditions.",
                     "season":"Rabi","water_mm":350,"duration":"90–100 days",
                     "profit":"High","market_price":55,"category":"Pulse",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":0.8,
                     "pest_risk":"Low","diseases":["Ascochyta Blight","Helicoverpa","Fusarium Wilt"]},
    "Kidney Beans": {"tip":"Needs moderate rainfall and well-drained loamy soil.",
                     "season":"Kharif","water_mm":500,"duration":"80–120 days",
                     "profit":"High","market_price":60,"category":"Pulse",
                     "soil_types":["Loamy","Sandy Loam"],"min_om":1.0,
                     "pest_risk":"Medium","diseases":["Bean Mosaic Virus","Rust","Anthracnose"]},
    "Pigeon Peas":  {"tip":"Very drought-tolerant. Suitable for semi-arid regions.",
                     "season":"Kharif","water_mm":400,"duration":"120–180 days",
                     "profit":"High","market_price":62,"category":"Pulse",
                     "soil_types":["Sandy Loam","Red Laterite"],"min_om":0.7,
                     "pest_risk":"Low","diseases":["Sterility Mosaic","Fusarium Wilt","Pod Borer"]},
    "Moth Beans":   {"tip":"Extremely drought-hardy. Thrives in hot, arid zones.",
                     "season":"Kharif","water_mm":250,"duration":"60–90 days",
                     "profit":"Medium","market_price":50,"category":"Pulse",
                     "soil_types":["Sandy","Sandy Loam"],"min_om":0.5,
                     "pest_risk":"Low","diseases":["Powdery Mildew","Aphids"]},
    "Mung Bean":    {"tip":"Short-duration crop. Ideal after the main kharif season.",
                     "season":"Zaid","water_mm":350,"duration":"60–75 days",
                     "profit":"High","market_price":72,"category":"Pulse",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":0.8,
                     "pest_risk":"Low","diseases":["Yellow Mosaic Virus","Cercospora Leaf Spot"]},
    "Black Gram":   {"tip":"Rich in protein. Prefers warm, humid conditions.",
                     "season":"Kharif / Rabi","water_mm":450,"duration":"65–90 days",
                     "profit":"High","market_price":68,"category":"Pulse",
                     "soil_types":["Loamy","Clay Loam"],"min_om":1.0,
                     "pest_risk":"Medium","diseases":["Yellow Mosaic Virus","Powdery Mildew","Aphids"]},
    "Lentil":       {"tip":"Cool-season crop. Fixes atmospheric nitrogen naturally.",
                     "season":"Rabi","water_mm":300,"duration":"80–120 days",
                     "profit":"High","market_price":58,"category":"Pulse",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":0.8,
                     "pest_risk":"Low","diseases":["Rust","Stemphylium Blight","Aphids"]},
    "Pomegranate":  {"tip":"Highly drought-tolerant once established.",
                     "season":"Perennial","water_mm":600,"duration":"5–7 years",
                     "profit":"Very High","market_price":90,"category":"Fruit",
                     "soil_types":["Sandy Loam","Loamy","Red Laterite"],"min_om":0.8,
                     "pest_risk":"Low","diseases":["Bacterial Blight","Fruit Borer","Aphids"]},
    "Banana":       {"tip":"Needs plenty of water and warm temperatures year-round.",
                     "season":"Perennial","water_mm":1800,"duration":"12–18 months",
                     "profit":"High","market_price":35,"category":"Fruit",
                     "soil_types":["Loamy","Clay Loam"],"min_om":2.0,
                     "pest_risk":"High","diseases":["Panama Wilt","Sigatoka","Banana Weevil"]},
    "Mango":        {"tip":"Thrives in tropical climates with a distinct dry season.",
                     "season":"Perennial","water_mm":900,"duration":"3–5 years",
                     "profit":"Very High","market_price":80,"category":"Fruit",
                     "soil_types":["Sandy Loam","Loamy","Red Laterite"],"min_om":1.0,
                     "pest_risk":"Medium","diseases":["Anthracnose","Mango Hoppers","Powdery Mildew"]},
    "Grapes":       {"tip":"Requires a long, warm, dry growing season.",
                     "season":"Perennial","water_mm":700,"duration":"3 years",
                     "profit":"Very High","market_price":85,"category":"Fruit",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":1.2,
                     "pest_risk":"High","diseases":["Downy Mildew","Powdery Mildew","Mealy Bug"]},
    "Watermelon":   {"tip":"Needs sandy soil, lots of sun, and warm days.",
                     "season":"Zaid","water_mm":500,"duration":"70–90 days",
                     "profit":"High","market_price":12,"category":"Fruit",
                     "soil_types":["Sandy","Sandy Loam"],"min_om":1.0,
                     "pest_risk":"Medium","diseases":["Fusarium Wilt","Aphids","Cucumber Beetle"]},
    "Muskmelon":    {"tip":"Prefers hot, dry weather and well-drained sandy loam.",
                     "season":"Zaid","water_mm":400,"duration":"75–100 days",
                     "profit":"High","market_price":15,"category":"Fruit",
                     "soil_types":["Sandy","Sandy Loam"],"min_om":0.8,
                     "pest_risk":"Medium","diseases":["Powdery Mildew","Aphids","Fruit Fly"]},
    "Apple":        {"tip":"Requires chilling hours in winter for proper fruiting.",
                     "season":"Perennial","water_mm":1100,"duration":"5–8 years",
                     "profit":"Very High","market_price":120,"category":"Fruit",
                     "soil_types":["Loamy","Sandy Loam"],"min_om":2.0,
                     "pest_risk":"High","diseases":["Scab","Fire Blight","Codling Moth"]},
    "Orange":       {"tip":"Subtropical climate with mild winters works best.",
                     "season":"Perennial","water_mm":1000,"duration":"3–5 years",
                     "profit":"High","market_price":45,"category":"Fruit",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":1.5,
                     "pest_risk":"Medium","diseases":["Citrus Canker","Greening","Psyllid"]},
    "Papaya":       {"tip":"Fast-growing. Sensitive to frost and waterlogging.",
                     "season":"Perennial","water_mm":1400,"duration":"10–12 months",
                     "profit":"High","market_price":20,"category":"Fruit",
                     "soil_types":["Sandy Loam","Loamy"],"min_om":1.5,
                     "pest_risk":"Medium","diseases":["Papaya Ringspot Virus","Mites","Anthracnose"]},
    "Coconut":      {"tip":"Coastal, humid tropics are ideal.",
                     "season":"Perennial","water_mm":1500,"duration":"5–6 years",
                     "profit":"High","market_price":30,"category":"Fruit",
                     "soil_types":["Sandy","Sandy Loam","Loamy"],"min_om":1.0,
                     "pest_risk":"Low","diseases":["Bud Rot","Rhinoceros Beetle","Leaf Blight"]},
    "Cotton":       {"tip":"Long growing season. Needs deep, well-drained soils.",
                     "season":"Kharif","water_mm":750,"duration":"150–180 days",
                     "profit":"High","market_price":62,"category":"Cash Crop",
                     "soil_types":["Black Cotton","Clay Loam"],"min_om":0.8,
                     "pest_risk":"Very High","diseases":["Bollworm","Whitefly","Alternaria Leaf Spot"]},
    "Jute":         {"tip":"Loves warm, humid climate with high rainfall.",
                     "season":"Kharif","water_mm":1600,"duration":"100–120 days",
                     "profit":"Medium","market_price":40,"category":"Cash Crop",
                     "soil_types":["Loamy","Clay Loam"],"min_om":1.2,
                     "pest_risk":"Medium","diseases":["Stem Rot","Yellow Mite","Semilooper"]},
    "Coffee":       {"tip":"Shade-grown at altitude. Consistent rainfall needed.",
                     "season":"Perennial","water_mm":1500,"duration":"3–4 years",
                     "profit":"Very High","market_price":200,"category":"Plantation",
                     "soil_types":["Loamy","Red Laterite"],"min_om":2.5,
                     "pest_risk":"Medium","diseases":["Coffee Berry Borer","Leaf Rust","Root Rot"]},
}

CROP_IDEAL = {
    "Rice":        dict(N=80, P=50, K=40, temperature=26, humidity=80, ph=6.2, rainfall=200),
    "Maize":       dict(N=85, P=65, K=50, temperature=24, humidity=65, ph=6.5, rainfall=85),
    "Chickpea":    dict(N=35, P=65, K=75, temperature=20, humidity=40, ph=6.5, rainfall=55),
    "Kidney Beans":dict(N=35, P=75, K=50, temperature=20, humidity=55, ph=6.8, rainfall=65),
    "Pigeon Peas": dict(N=35, P=55, K=40, temperature=23, humidity=50, ph=6.2, rainfall=70),
    "Moth Beans":  dict(N=35, P=45, K=30, temperature=30, humidity=35, ph=7.0, rainfall=40),
    "Mung Bean":   dict(N=35, P=55, K=30, temperature=30, humidity=65, ph=6.8, rainfall=55),
    "Black Gram":  dict(N=35, P=55, K=30, temperature=30, humidity=70, ph=6.8, rainfall=65),
    "Lentil":      dict(N=25, P=55, K=30, temperature=19, humidity=68, ph=7.0, rainfall=45),
    "Pomegranate": dict(N=30, P=15, K=40, temperature=24, humidity=72, ph=6.5, rainfall=80),
    "Banana":      dict(N=100,P=70, K=65, temperature=27, humidity=80, ph=6.2, rainfall=150),
    "Mango":       dict(N=30, P=30, K=45, temperature=31, humidity=50, ph=6.5, rainfall=85),
    "Grapes":      dict(N=30, P=20, K=45, temperature=22, humidity=67, ph=6.7, rainfall=65),
    "Watermelon":  dict(N=100,P=65, K=50, temperature=30, humidity=72, ph=6.5, rainfall=60),
    "Muskmelon":   dict(N=100,P=65, K=50, temperature=33, humidity=92, ph=6.7, rainfall=40),
    "Apple":       dict(N=10, P=25, K=40, temperature=10, humidity=87, ph=6.0, rainfall=150),
    "Orange":      dict(N=30, P=15, K=15, temperature=20, humidity=77, ph=6.7, rainfall=130),
    "Papaya":      dict(N=50, P=50, K=50, temperature=28, humidity=80, ph=6.7, rainfall=150),
    "Coconut":     dict(N=10, P=5,  K=40, temperature=30, humidity=80, ph=6.5, rainfall=175),
    "Cotton":      dict(N=120,P=40, K=30, temperature=27, humidity=60, ph=7.0, rainfall=90),
    "Jute":        dict(N=80, P=50, K=50, temperature=29, humidity=80, ph=6.5, rainfall=200),
    "Coffee":      dict(N=120,P=120,K=120,temperature=21, humidity=60, ph=6.2, rainfall=150),
}

# Soil type properties
SOIL_TYPES = {
    "Sandy":          {"texture":"Coarse","drainage":"Excellent","water_hold":"Very Low",
                       "fertility":"Low","color":"#f4d03f","desc":"Light, dry soil. Drains fast, low nutrients."},
    "Sandy Loam":     {"texture":"Medium-Coarse","drainage":"Good","water_hold":"Low",
                       "fertility":"Medium","color":"#e67e22","desc":"Good drainage, moderate fertility. Versatile."},
    "Loamy":          {"texture":"Medium","drainage":"Good","water_hold":"Medium",
                       "fertility":"High","color":"#784212","desc":"Ideal for most crops. Balanced texture."},
    "Clay Loam":      {"texture":"Medium-Fine","drainage":"Moderate","water_hold":"High",
                       "fertility":"High","color":"#922b21","desc":"Nutrient-rich, retains moisture well."},
    "Clay":           {"texture":"Fine","drainage":"Poor","water_hold":"Very High",
                       "fertility":"Very High","color":"#641e16","desc":"Heavy soil, prone to waterlogging."},
    "Black Cotton":   {"texture":"Fine","drainage":"Poor","water_hold":"Very High",
                       "fertility":"High","color":"#1a1a1a","desc":"Highly fertile. Cracks when dry."},
    "Red Laterite":   {"texture":"Medium","drainage":"Good","water_hold":"Low",
                       "fertility":"Low","color":"#c0392b","desc":"Acidic, iron-rich. Suitable for tropical crops."},
    "Silty Loam":     {"texture":"Medium-Fine","drainage":"Moderate","water_hold":"High",
                       "fertility":"High","color":"#aab7b8","desc":"Smooth texture, high fertility, moderate drainage."},
}

# Organic matter levels
OM_LEVELS = {
    "Very Low (<0.5%)":  {"score":1,"label":"Critical","color":"#e53935","advice":"Add 10–15 t/ha FYM or compost immediately."},
    "Low (0.5–1.0%)":   {"score":2,"label":"Poor","color":"#f57c00","advice":"Apply 5–8 t/ha organic matter per season."},
    "Medium (1.0–2.0%)":{"score":3,"label":"Adequate","color":"#fbc02d","advice":"Maintain with crop residue incorporation."},
    "High (2.0–3.5%)":  {"score":4,"label":"Good","color":"#388e3c","advice":"Keep adding green manure to sustain levels."},
    "Very High (>3.5%)":{"score":5,"label":"Excellent","color":"#1b5e20","advice":"Ideal. Monitor to avoid excess nitrogen release."},
}

OM_VALUE_MAP = {
    "Very Low (<0.5%)": 0.3,
    "Low (0.5–1.0%)":   0.75,
    "Medium (1.0–2.0%)":1.5,
    "High (2.0–3.5%)":  2.75,
    "Very High (>3.5%)":4.0,
}

# Water source options
WATER_SOURCES = [
    "Rainfed only",
    "Borewell / Groundwater",
    "Canal / River",
    "Drip Irrigation",
    "Sprinkler Irrigation",
    "Tank / Pond",
]

# i18n strings
LANGUAGES = {
    "English 🇬🇧":    "en",
    "हिंदी 🇮🇳":      "hi",
    "తెలుగు 🇮🇳":     "te",
    "தமிழ் 🇮🇳":     "ta",
    "বাংলা 🇮🇳":      "bn",
    "मराठी 🇮🇳":      "mr",
    "ਪੰਜਾਬੀ 🇮🇳":    "pa",
    "Español 🇪🇸":    "es",
    "Français 🇫🇷":   "fr",
    "中文 🇨🇳":        "zh",
}

I18N = {
    "app_title":        {"en":"🌾 Smart Crop Advisor","hi":"🌾 स्मार्ट फसल सलाहकार",
                         "te":"🌾 స్మార్ట్ పంట సలహాదారు","ta":"🌾 ஸ்மார்ட் பயிர் ஆலோசகர்",
                         "bn":"🌾 স্মার্ট ফসল উপদেষ্টা","mr":"🌾 स्मार्ट पीक सल्लागार",
                         "pa":"🌾 ਸਮਾਰਟ ਫਸਲ ਸਲਾਹਕਾਰ","es":"🌾 Asesor de Cultivos",
                         "fr":"🌾 Conseiller Agricole","zh":"🌾 智能作物顾问"},
    "subtitle":         {"en":"AI-powered crop recommendation · 22 crops · Random Forest",
                         "hi":"AI-आधारित फसल अनुशंसा · 22 फसलें · रैंडम फॉरेस्ट",
                         "te":"AI-ఆధారిత పంట సిఫార్సు · 22 పంటలు","ta":"AI-சார்ந்த பயிர் பரிந்துரை · 22 பயிர்கள்",
                         "bn":"AI-চালিত ফসল সুপারিশ · ২২ ফসল","mr":"AI-आधारित पीक शिफारस · 22 पिके",
                         "pa":"AI-ਅਧਾਰਿਤ ਫਸਲ ਸਿਫ਼ਾਰਸ਼ · 22 ਫਸਲਾਂ","es":"Recomendación de cultivos con IA · 22 cultivos",
                         "fr":"Recommandation de cultures par IA · 22 cultures","zh":"AI驱动作物推荐 · 22种作物"},
    "predict_tab":      {"en":"🔍 Predict","hi":"🔍 भविष्यवाणी","te":"🔍 అంచనా","ta":"🔍 முன்னறிவிப்பு",
                         "bn":"🔍 পূর্বাভাস","mr":"🔍 अंदाज","pa":"🔍 ਅੰਦਾਜ਼ਾ","es":"🔍 Predecir",
                         "fr":"🔍 Prédire","zh":"🔍 预测"},
    "analysis_tab":     {"en":"📊 Analysis","hi":"📊 विश्लेषण","te":"📊 విశ్లేషణ","ta":"📊 பகுப்பாய்வு",
                         "bn":"📊 বিশ্লেষণ","mr":"📊 विश्लेषण","pa":"📊 ਵਿਸ਼ਲੇਸ਼ਣ","es":"📊 Análisis",
                         "fr":"📊 Analyse","zh":"📊 分析"},
    "soil_tab":         {"en":"🪨 Soil & OM","hi":"🪨 मिट्टी और OM","te":"🪨 నేల & OM",
                         "ta":"🪨 மண் & OM","bn":"🪨 মাটি ও OM","mr":"🪨 माती व सेंद्रिय पदार्थ",
                         "pa":"🪨 ਮਿੱਟੀ ਅਤੇ OM","es":"🪨 Suelo & MO","fr":"🪨 Sol & MO","zh":"🪨 土壤与有机质"},
    "pest_tab":         {"en":"🐛 Pest & Disease","hi":"🐛 कीट और रोग","te":"🐛 తెగులు & వ్యాధి",
                         "ta":"🐛 பூச்சி & நோய்","bn":"🐛 কীটপতঙ্গ ও রোগ","mr":"🐛 कीड व रोग",
                         "pa":"🐛 ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀ","es":"🐛 Plagas & Enfermedades",
                         "fr":"🐛 Ravageurs & Maladies","zh":"🐛 病虫害"},
    "water_tab":        {"en":"💧 Water Planner","hi":"💧 जल योजनाकार","te":"💧 నీటి ప్రణాళిక",
                         "ta":"💧 நீர் திட்டமிடல்","bn":"💧 জল পরিকল্পনাকারী","mr":"💧 जल नियोजक",
                         "pa":"💧 ਪਾਣੀ ਯੋਜਨਾਕਾਰ","es":"💧 Planificador de Agua",
                         "fr":"💧 Planificateur d'Eau","zh":"💧 灌溉规划"},
    "explorer_tab":     {"en":"🗺️ Explorer","hi":"🗺️ एक्सप्लोरर","te":"🗺️ అన్వేషకుడు",
                         "ta":"🗺️ ஆய்வாளர்","bn":"🗺️ অন্বেষক","mr":"🗺️ एक्सप्लोरर",
                         "pa":"🗺️ ਐਕਸਪਲੋਰਰ","es":"🗺️ Explorador","fr":"🗺️ Explorateur","zh":"🗺️ 探索"},
    "history_tab":      {"en":"📜 History","hi":"📜 इतिहास","te":"📜 చరిత్ర","ta":"📜 வரலாறு",
                         "bn":"📜 ইতিহাস","mr":"📜 इतिहास","pa":"📜 ਇਤਿਹਾਸ",
                         "es":"📜 Historial","fr":"📜 Historique","zh":"📜 历史"},
    "recommend_btn":    {"en":"🌱 Get Recommendation","hi":"🌱 सिफारिश प्राप्त करें",
                         "te":"🌱 సిఫార్సు పొందండి","ta":"🌱 பரிந்துரை பெறு",
                         "bn":"🌱 সুপারিশ পান","mr":"🌱 शिफारस मिळवा",
                         "pa":"🌱 ਸਿਫ਼ਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ","es":"🌱 Obtener Recomendación",
                         "fr":"🌱 Obtenir Recommandation","zh":"🌱 获取推荐"},
    "recommended_crop": {"en":"Recommended Crop","hi":"अनुशंसित फसल","te":"సిఫార్సు చేయబడిన పంట",
                         "ta":"பரிந்துரைக்கப்பட்ட பயிர்","bn":"প্রস্তাবিত ফসল","mr":"शिफारस केलेले पीक",
                         "pa":"ਸਿਫ਼ਾਰਸ਼ੀ ਫਸਲ","es":"Cultivo Recomendado",
                         "fr":"Culture Recommandée","zh":"推荐作物"},
    "confidence":       {"en":"Confidence","hi":"विश्वास","te":"విశ్వాసం","ta":"நம்பகத்தன்மை",
                         "bn":"আস্থা","mr":"विश्वासार्हता","pa":"ਭਰੋਸਾ",
                         "es":"Confianza","fr":"Confiance","zh":"置信度"},
    "soil_nutrients":   {"en":"🧪 Soil Nutrients (kg/ha)","hi":"🧪 मृदा पोषक तत्व (kg/ha)",
                         "te":"🧪 నేల పోషకాలు (kg/ha)","ta":"🧪 மண் ஊட்டச்சத்துகள்",
                         "bn":"🧪 মাটির পুষ্টি উপাদান (kg/ha)","mr":"🧪 मातीचे पोषक (kg/ha)",
                         "pa":"🧪 ਮਿੱਟੀ ਪੌਸ਼ਟਿਕ ਤੱਤ (kg/ha)","es":"🧪 Nutrientes del Suelo",
                         "fr":"🧪 Nutriments du Sol","zh":"🧪 土壤养分 (kg/ha)"},
    "environment":      {"en":"🌡️ Environment","hi":"🌡️ पर्यावरण","te":"🌡️ పర్యావరణం",
                         "ta":"🌡️ சூழல்","bn":"🌡️ পরিবেশ","mr":"🌡️ पर्यावरण",
                         "pa":"🌡️ ਵਾਤਾਵਰਣ","es":"🌡️ Entorno","fr":"🌡️ Environnement","zh":"🌡️ 环境"},
    "alerts_title":     {"en":"🔔 Smart Alerts","hi":"🔔 स्मार्ट अलर्ट","te":"🔔 స్మార్ట్ అలర్ట్‌లు",
                         "ta":"🔔 ஸ்மார்ட் எச்சரிக்கைகள்","bn":"🔔 স্মার্ট সতর্কতা",
                         "mr":"🔔 स्मार्ट सूचना","pa":"🔔 ਸਮਾਰਟ ਅਲਰਟ",
                         "es":"🔔 Alertas Inteligentes","fr":"🔔 Alertes Intelligentes","zh":"🔔 智能提醒"},
}

def t(key: str, lang: str) -> str:
    """Translate a key to the given language, fall back to English."""
    return I18N.get(key, {}).get(lang, I18N.get(key, {}).get("en", key))
